version: '3'

services:
  flask-services:
    build: ./flask
    links:
      - db
    volumes:
      - ./flask
    ports:
      - 5000:5000
      - 5001:5001

  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    links:
      - flask-services
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    links:
      - prometheus
    ports:
      - 3000:3000
