apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    name: mysql-secret
    app: mysql
  namespace: default
type: Opaque
data:
  root-password: cGFzc3dvcmQK
  database-name: Y2hhdAo=
  user-name: ZGJfdXNlcgo=
  db-password: cGFzc3dvcmQK